name: Build, Push, and Deploy Create Availability

on:
  push:
    branches: [ "QA" ]
    paths:
      - "BACKEND/link-management/delete-link-service**"  # Cambios en esta carpeta activan el pipeline

jobs:
  build-and-push-lm-delete:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd BACKEND/link-management/delete-link-service
          docker build \
            --label "commit_sha=${{ github.sha }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/lm-delete-microservices:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lm-delete-microservices:latest

  deploy-aws-lm-delete:
    runs-on: ubuntu-latest
    needs: build-and-push-lm-delete  # Este job se ejecuta solo despuÃ©s de que se complete el build
    steps:
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy Docker Container on AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_M2 }} << EOF
          sudo yum update -y
          if ! command -v docker &> /dev/null; then
            sudo yum install -y docker
          fi
          sudo systemctl start docker
          sudo systemctl enable docker
          
          sudo docker stop lm-delete-microservices || true
          sudo docker rm lm-delete-microservices || true
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/lm-delete-microservices:latest
          sudo docker run -d -p 8086:8086 --name lm-delete-microservices ${{ secrets.DOCKER_USERNAME }}/lm-delete-microservices:latest
          
          sudo docker ps -a
          EOF
